routes/web.php
        Route::post('login', ['uses' => 'Auth\AuthController@postLogin', 'as' => 'post.login']);
        Route::post('auth/register', ['uses' => 'Auth\AuthController@postRegister', 'as' => 'post.register']);
        Route::post('password/reset', ['uses' => 'Auth\PasswordController@reset', 'as' => 'post.reset']);
        Route::get('auth/logout', ['uses' => 'Auth\AuthController@getLogout', 'as' => 'get.logout']);
        Route::get('social/login/redirect/{provider}/{redirect?}', ['uses' => 'Auth\AuthController@redirectToProvider', 'as' => 'social.login']);
        Route::get('social/login/{provider}', ['as'=>'social.login.callback', 'uses'=>'Auth\AuthController@handleProviderCallback']);
        Route::get('social-sync', ['as'=>'social.sync', 'uses'=>'Client\helpdesk\GuestController@sync']);
    });

    /*
      |-------------------------------------------------------------------------------
      | @Anjali
      |-------------------------------------------------------------------------------
      | Here is defining entire routes for the Admin Panel
      |
     */

    /*Route::get('auth/login',
        ['as' => 'login', 'uses' => 'Auth/AuthController@getLogin']);*/

    Route::get('password/email/{one?}/{two?}/{three?}/{four?}/{five?}', ['as' => 'password.email', 'uses' => 'Auth\PasswordController@getEmail']);
    Breadcrumbs::register('password.email', function ($breadcrumbs) {
        $breadcrumbs->parent('/');
        $breadcrumbs->push('Login', url('auth/login'));
        $breadcrumbs->push('Forgot Password', url('password/email'));
    });

    // register page
    Route::get('auth/register/{one?}/{two?}/{three?}/{four?}/{five?}', ['as' => 'auth.register', 'uses' => 'Auth\AuthController@getRegister']);
    Breadcrumbs::register('auth.register', function ($breadcrumbs) {
        $breadcrumbs->parent('/');
        $breadcrumbs->push('Login', url('auth/login'));
        $breadcrumbs->push('Create Account', url('auth/register'));
    });

    // Auth login
    Route::get('auth/login/{one?}/{two?}/{three?}/{four?}/{five?}', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
    Breadcrumbs::register('auth.login', function ($breadcrumbs) {
        $breadcrumbs->parent('/');
        $breadcrumbs->push('Create Account', url('auth/register'));
        $breadcrumbs->push('Login', url('auth/login'));
    });




    Route::get('account/activate/{token}', ['as' => 'account.activate', 'uses' => 'Auth\AuthController@accountActivate']);
    Route::get('getmail/{token}', 'Auth\AuthController@getMail');
    Route::get('verify-otp', ['as' => 'otp-verification', 'uses' => 'Auth\AuthController@getVerifyOTP']);
    Route::post('verify-otp', ['as' => 'otp-verification', 'uses' => 'Auth\AuthController@verifyOTP']);
    Route::post('resend/opt', ['as' => 'resend-otp', 'uses' => 'Auth\AuthController@resendOTP']);

    /*
      |-------------------------------------------------------------------------------
      | Admin Routes
      |-------------------------------------------------------------------------------
      | Here is defining entire routes for the Admin Panel
      |
     */
    Route::group(['middleware' => 'roles', 'middleware' => 'auth', 'middleware' => 'install', 'middleware' => 'update'], function () {
        //Notification marking
        Route::post('mark-read/{id}', 'Common\NotificationController@markRead');
        Route::post('mark-all-read/{id}', 'Common\NotificationController@markAllRead');

        Route::get('notifications-list', ['as' => 'notification.list', 'uses' => 'Common\NotificationController@show']);
        Route::post('notification-delete/{id}', ['as' => 'notification.delete', 'uses' => 'Common\NotificationController@delete']);
        Route::get('notifications-list/delete', ['as' => 'notification.delete.all', 'uses' => 'Common\NotificationController@deleteAll']);

        Route::get('settings-notification', ['as' => 'notification.settings', 'uses' => 'Admin\helpdesk\SettingsController@notificationSettings']);
        Route::get('delete-read-notification', 'Admin\helpdesk\SettingsController@deleteReadNoti');
        Route::post('delete-notification-log', 'Admin\helpdesk\SettingsController@deleteNotificationLog');
        // resource is a function to process create,edit,read and delete
        Route::resource('groups', 'Admin\helpdesk\GroupController'); // for group module, for CRUD

        Route::resource('departments', 'Admin\helpdesk\DepartmentController'); // for departments module, for CRUD

        Route::resource('teams', 'Admin\helpdesk\TeamController'); // in teams module, for CRUD
        Route::get('/teams/show/{id}', ['as' => 'teams.show', 'uses' => 'Admin\helpdesk\TeamController@show']); /*  Get Team View */
        Breadcrumbs::register('teams.show', function ($breadcrumbs) {
            $breadcrumbs->parent('teams.index');
            $breadcrumbs->push(Lang::get('lang.show'), url('teams/{teams}/show'));
        });
        Route::get('getshow/{id}', ['as' => 'teams.getshow.list', 'uses' => 'Admin\helpdesk\TeamController@getshow']);
        Route::resource('agents', 'Admin\helpdesk\AgentController'); // in agents module, for CRUD

        Route::resource('emails', 'Admin\helpdesk\EmailsController'); // in emails module, for CRUD

        Route::resource('banlist', 'Admin\helpdesk\BanlistController'); // in banlist module, for CRUD

        Route::get('banlist/delete/{id}', ['as' => 'banlist.delete', 'uses' => 'Admin\helpdesk\BanlistController@delete']); // in banlist module, for CRUD
        /*
         * Templates
         */

        Route::resource('templates', 'Common\TemplateController');
        Route::get('get-templates', 'Common\TemplateController@GetTemplates');
        Route::get('templates-delete', 'Common\TemplateController@destroy');
        Route::get('testmail/{id}', 'Common\TemplateController@mailtest');
        Route::resource('template-sets', 'Common\TemplateSetController'); // in template module, for CRUD
        Route::get('delete-sets/{id}', ['as' => 'sets.delete', 'uses' => 'Common\TemplateSetController@deleteSet']);
        Route::get('show-template/{id}', ['as' => 'show.templates', 'uses' => 'Common\TemplateController@showTemplate']);
        Route::get('activate-templateset/{name}', ['as' => 'active.template-set', 'uses' => 'Common\TemplateSetController@activateSet']);
        Route::resource('template', 'Admin\helpdesk\TemplateController'); // in template module, for CRUD
        Route::get('list-directories', 'Admin\helpdesk\TemplateController@listdirectories');
        Route::get('activate-set/{dir}', ['as' => 'active.set', 'uses' => 'Admin\helpdesk\TemplateController@activateset']);
        Route::get('list-templates/{template}/{directory}', ['as' => 'template.list', 'uses' => 'Admin\helpdesk\TemplateController@listtemplates']);
        Route::get('read-templates/{template}/{directory}', ['as' => 'template.read', 'uses' => 'Admin\helpdesk\TemplateController@readtemplate']);
        Route::patch('write-templates/{contents}/{directory}', ['as' => 'template.write', 'uses' => 'Admin\helpdesk\TemplateController@writetemplate']);
        Route::post('create-templates', ['as' => 'template.createnew', 'uses' => 'Admin\helpdesk\TemplateController@createtemplate']);
        Route::get('delete-template/{template}/{path}', ['as' => 'templates.delete', 'uses' => 'Admin\helpdesk\TemplateController@deletetemplate']);
        Route::get('getdiagno', ['as' => 'getdiagno', 'uses' => 'Admin\helpdesk\TemplateController@formDiagno']); // for getting form for diagnostic

        Route::post('postdiagno', ['as' => 'postdiagno', 'uses' => 'Admin\helpdesk\TemplateController@postDiagno']); // for getting form for diagnostic
        Route::resource('helptopic', 'Admin\helpdesk\HelptopicController'); // in helptopics module, for CRUD

        Route::resource('sla', 'Admin\helpdesk\SlaController'); // in SLA Plan module, for CRUD

        Route::resource('forms', 'Admin\helpdesk\FormController');
        Route::get('forms/add-child/{formid}', ['as' => 'forms.add.child', 'uses' => 'Admin\helpdesk\FormController@addChildForm']);
        Route::post('forms/field/{fieldid}/child', [
            'as'   => 'forms.field.child',
            'uses' => 'Admin\helpdesk\FormController@addChild',
        ]);
        Route::get('forms/render/child', [
            'as'   => 'forms.field.child',
            'uses' => 'Admin\helpdesk\FormController@renderChild',
        ]);

        Route::get('delete-forms/{id}', ['as' => 'forms.delete', 'uses' => 'Admin\helpdesk\FormController@delete']);
        //$router->model('id','getcompany');
        Route::get('job-scheduler', ['as' => 'get.job.scheder', 'uses' => 'Admin\helpdesk\SettingsController@getSchedular']); //to get ob scheduler form page

        Route::patch('post-scheduler', ['as' => 'post.job.scheduler', 'uses' => 'Admin\helpdesk\SettingsController@postSchedular']); //to update job scheduler
        Route::get('agent-profile-page/{id}', ['as' => 'agent.profile.page', 'uses' => 'Admin\helpdesk\AgentController@agent_profile']);
        Route::get('getcompany', ['as' => 'getcompany', 'uses' => 'Admin\helpdesk\SettingsController@getcompany']); // direct to company setting page

        Route::patch('postcompany/{id}', 'Admin\helpdesk\SettingsController@postcompany'); // Updating the Company table with requests
        Route::get('delete-logo', ['as' => 'delete.logo', 'uses' => 'Admin\helpdesk\SettingsController@deleteLogo']); // deleting a logo
        Route::get('getsystem', ['as' => 'getsystem', 'uses' => 'Admin\helpdesk\SettingsController@getsystem']); // direct to system setting page

        Route::patch('postsystem/{id}', 'Admin\helpdesk\SettingsController@postsystem'); // Updating the System table with requests
        Route::get('getticket', ['as' => 'getticket', 'uses' => 'Admin\helpdesk\SettingsController@getticket']); // direct to ticket setting page

app/Http/Controllers/Common/ApiSettings.php
<?php

namespace App\Http\Controllers\Common;

use App\Http\Controllers\Controller;
use App\Model\Api\ApiSetting;
use App\Model\helpdesk\Ticket\Ticket_Thread;
use App\Model\helpdesk\Ticket\Tickets;
use DB;
use Exception;
use Illuminate\Http\Request;
use Input;
use Log;

class ApiSettings extends Controller
{
    public $api;

    public function __construct()
    {
        $this->middleware('auth', ['except' => ['ticketDetailEvent', 'postHook', 'postForm']]);
        $this->middleware('roles', ['except' => ['ticketDetailEvent', 'postHook', 'postForm']]);

        $api = new ApiSetting();
        $this->api = $api;
    }

    public function show()
    {
        try {
            /* fetch the values of system from system table */
            $systems = DB::table('settings_system')->whereId('1')->first();
            $details = [];
            $ticket_detail = '';
            $settings = $this->api;
            if ($settings->get()->count() > 0) {
                $details = $this->api->pluck('value', 'key')->toArray();
            }
            if (array_key_exists('ticket_detail', $details)) {
                $ticket_detail = $details['ticket_detail'];
            }

            return view('themes.default1.common.api.settings', compact('ticket_detail', 'systems'));
        } catch (Exception $ex) {
            return redirect()->back()->with('fails', $ex->getMessage());
        }
    }

    public function postSettings(Request $request)
    {
        $this->validate($request, [
            'ticket_detail' => 'url',
        ]);

        try {
            // dd($request->input());
            DB::table('settings_system')
            ->where('id', 1)
            ->update(['api_enable'  => Input::get('api_enable'),
                'api_key_mandatory' => Input::get('api_key_mandatory'),
                'api_key'           => Input::get('api_key'), ]);
            $settings = $this->api;
            if ($settings->get()->count() > 0) {
                foreach ($settings->get() as $set) {
                    $set->delete();
                }
            }
            foreach ($request->except('_token') as $key => $value) {
                $settings->create(['key' => $key, 'value' => $value]);
            }

            return redirect()->back()->with('success', 'Updated Successfully');
        } catch (Exception $ex) {
            return redirect()->back()->with('fails', $ex->getMessage());
        }
    }

    public function ticketDetailEvent($detail)
    {
        try {
            $ticket = new Tickets();
            $ticketid = $detail->ticket_id;
            $data = $ticket
                    ->join('ticket_thread', function ($join) use ($ticketid) {
                        $join->on('tickets.id', '=', 'ticket_thread.ticket_id')
                        ->where('ticket_thread.ticket_id', '=', $ticketid);
                    })
                    ->join('users', 'ticket_thread.user_id', '=', 'users.id')
                    ->select('ticket_thread.title', 'ticket_thread.body', 'users.first_name', 'users.last_name', 'users.email', 'ticket_thread.created_at')
                    ->get()
                    ->toJson();
            $this->postHook($data);
        } catch (Exception $ex) {
            dd($ex);

            throw new Exception($ex->getMessage());
        }
    }

    public function postHook($data)
    {
        try {
            $set = $this->api->where('key', 'ticket_detail')->first();
            if ($set) {
                if ($set->value) {
                    $this->postForm($data, $set->value);
                }
            }
        } catch (Exception $ex) {
            dd($ex);

            throw new Exception($ex->getMessage());
        }
    }

    public function postForm($data, $url)
    {
        try {
            $post_data = [
                'data' => $data,
            ];
            $upgrade_controller = new \App\Http\Controllers\Update\UpgradeController();
            $upgrade_controller->postCurl($url, $post_data);
            Log::info('ticket details has send to : '.$url.' and details are : '.$data);
        } catch (Exception $ex) {
            throw new Exception($ex->getMessage());
        }
    }
}

app/Http/Controllers/Common/CommonMailer.php
<?php

namespace App\Http\Controllers\Common;

use Exception;

class CommonMailer
{
    public function setSmtpDriver($config)
    {
        try {
            if (!$config) {
                return false;
            }
            $https = [];
            $https['ssl']['verify_peer'] = false;
            $https['ssl']['verify_peer_name'] = false;
            $transport = new \Swift_SmtpTransport($config['host'], $config['port'], $config['security']);
            $transport->setUsername($config['username']);
            $transport->setPassword($config['password']);
            $transport->setStreamOptions($https);
            $set = new \Swift_Mailer($transport);

            // Set the mailer
            \Mail::setSwiftMailer($set);

            return true;
        } catch (Exception $e) {
            loging('mail-config', $e->getMessage());

            return $e->getMessage();
        }
    }

    public function setMailGunDriver($config)
    {
        if (!$config) {
            return false;
        }

        return true;
    }
}

app/Http/Controllers/Common/ExcelController.php
<?php

namespace App\Http\Controllers\Common;

use App\Http\Controllers\Controller;
use Excel;
use Exception;

class ExcelController extends Controller
{
    public function export($filename, $data)
    {
        if (count($data) == 0) {
            throw new Exception('No data');
        }
        Excel::create($filename, function ($excel) use ($data) {
            $excel->sheet('sheet', function ($sheet) use ($data) {
                $sheet->fromArray($data);
            });
        })->export('xls');
    }
}

app/Http/Controllers/Common/FileuploadController.php
<?php

namespace App\Http\Controllers\Common;

use App\Http\Controllers\Controller;

class FileuploadController extends Controller
{
    public function __construct()
    {
        // checking authentication
        $this->middleware('auth');
        // checking if role is agent
        $this->middleware('role.agent');
    }

    // Returns a file size limit in bytes based on the PHP upload_max_filesize
    // and post_max_size
    public function file_upload_max_size()
    {
        static $max_size = -1;

        if ($max_size < 0) {
            // Start with post_max_size.
            $max_size_in_bytes = $this->parse_size(ini_get('post_max_size'));
            $max_size_in_actual = ini_get('post_max_size');

            // If upload_max_size is less, then reduce. Except if upload_max_size is
            // zero, which indicates no limit.
            $upload_max = $this->parse_size(ini_get('upload_max_filesize'));
            if ($upload_max > 0 && $upload_max < $max_size) {
                $max_size_in_bytes = $upload_max;
                $max_size_in_actual = ini_get('upload_max_filesize');
            }
        }

        return ['0' => $max_size_in_bytes, '1' => $max_size_in_actual];
//        return $max_size_in_bytes;
    }

    public function parse_size($size)
    {
        $unit = preg_replace('/[^bkmgtpezy]/i', '', $size); // Remove the non-unit characters from the size.
        $size = preg_replace('/[^0-9\.]/', '', $size); // Remove the non-numeric characters from the size.
        if ($unit) {
            // Find the position of the unit in the ordered string which is the power of magnitude to multiply a kilobyte by.
            return round($size * pow(1024, stripos('bkmgtpezy', $unit[0])));
        } else {
            return round($size);
        }
    }
}

app/Http/Controllers/Common/Socialite.php
<?php

namespace App\Http\Controllers\Common;

use Socialite;

class Socialite extends Socialite
{
}

resources/views/themes/default1/common/template/create.blade.php
@extends('themes.default1.admin.layout.admin')
@section('content')
<div class="box box-primary">

    <div class="content-header">
        {!! Form::open(['route'=>'templates.store','method'=>'post']) !!}
        <h4>{{Lang::get('lang.templates')}}	{!! Form::submit(Lang::get('lang.save'),['class'=>'form-group btn btn-primary pull-right'])!!}</h4>

    </div>

    <div class="box-body">

        <div class="row">

            <div class="col-md-12">

                @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif

                @if(Session::has('success'))
                <div class="alert alert-success alert-dismissable">
                    <i class="fa fa-ban"></i>
                    <b>{{Lang::get('lang.alert')}}!</b> {{Lang::get('lang.success')}}.
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{Session::get('success')}}
                </div>
                @endif
                <!-- fail lang -->
                @if(Session::has('fails'))
                <div class="alert alert-danger alert-dismissable">
                    <i class="fa fa-ban"></i>
                    <b>{{Lang::get('lang.alert')}}!</b> {{Lang::get('lang.failed')}}.
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{Session::get('fails')}}
                </div>
                @endif

                <div class="row">

                    <div class="col-md-6 form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <!-- first name -->
                        {!! Form::label('name',Lang::get('lang.name'),['class'=>'required']) !!}
                        {!! Form::text('name',null,['class' => 'form-control']) !!}

                    </div>

                    <div class="col-md-6 form-group {{ $errors->has('type') ? 'has-error' : '' }}">
                        <!-- last name -->
                        {!! Form::label('type',Lang::get('lang.template-types'),['class'=>'required']) !!}
                        {!! Form::select('type',[''=>'Select','Type'=>$type],null,['class' => 'form-control']) !!}

                    </div>
                                        

                </div>
<!--                <div class="row">
                    <div class="col-md-12 form-group {{ $errors->has('subject') ? 'has-error' : '' }}">
         
                        {!! Form::label('subject',Lang::get('lang.subject')) !!}
                        {!! Form::text('subject',null,['class' => 'form-control']) !!}

                    </div>
                </div>-->

                <div class="row">
                    <div class="col-md-12 form-group {{ $errors->has('message') ? 'has-error' : '' }}">
                       
                        
                        {!! Form::label('message',Lang::get('lang.content'),['class'=>'required']) !!}
                        {!! Form::textarea('message',null,['class'=>'form-control','id'=>'textarea']) !!}
                       
                    </div>


                </div>

            </div>

        </div>

    </div>

</div>


{!! Form::close() !!}
@stop

resources/views/themes/default1/common/template/edit.blade.php
@extends('themes.default1.admin.layout.admin')

@section('PageHeader')
<h1>{!! Lang::get('lang.templates') !!}</h1>
@stop

@section('content')
{!! Form::model($template,['url'=>'templates/'.$template->id,'method'=>'patch']) !!}
<div class="box box-primary">
    <div class="box-header with-border">

        <h3 class="box-title">{{Lang::get('lang.edit_template')}}</h4>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <i class="fa fa-ban"></i>  
                    <strong>{!! Lang::get('lang.alert') !!} !</strong>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                @if(Session::has('success'))
                <div class="alert alert-success alert-dismissable">
                    <i class="fa fa-check-circle"></i>  
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{Session::get('success')}}
                </div>
                @endif
                <!-- fail lang -->
                @if(Session::has('fails'))
                <div class="alert alert-danger alert-dismissable">
                    <i class="fa fa-ban"></i>
                    <b>{{Lang::get('lang.alert')}}!</b>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{Session::get('fails')}}
                </div>
                @endif
                <div class="row">
                    <div class="col-md-12 form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <!-- first name -->
                        <p class="lead">{!! $template->name !!}</p>
                    </div>
                    <div class="col-md-4 form-group {{ $errors->has('type') ? 'has-error' : '' }}">
                        <!-- last name -->
                        {!! Form::label('type',Lang::get('lang.template-types'),['class'=>'required']) !!}<span style="color:red;">*</span>
                        {!! Form::select('type',[''=>'Select','Type'=>$type],null,['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 form-group {{ $errors->has('subject') ? 'has-error' : '' }}">
                        {!! Form::label('subject',Lang::get('lang.subject')) !!}
                        {!! Form::text('subject',null,['class' => 'form-control', 'id' =>'subject']) !!}
                    </div>
                    <div class="col-md-3 form-group" id = "use-subject">
                        <br/>
                        {!! Form::hidden('variable','0') !!}
                        {!! Form::checkbox('variable','1') !!}
                        {!! Form::label('subject',Lang::get('lang.use_subject')) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 form-group {{ $errors->has('message') ? 'has-error' : '' }}">
                        {!! Form::label('message',Lang::get('lang.content'),['class'=>'required']) !!}<span style="color:red;">*</span>
                        {!! Form::textarea('message',null,['class'=>'form-control','id'=>'textarea']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        {!! Form::submit(Lang::get('lang.update'),['class'=>'form-group btn btn-primary'])!!}
    </div>
</div>
{!! Form::close() !!}

<script>
    $(document).ready(function() {
        $("#subject").keyup(function() {
            var subject = document.getElementById('subject').value;
            if (subject) {
                $("#use-subject").show();
            } else {
                $("#use-subject").hide();
            }
        });
    });
</script>
@stop

resources/views/themes/default1/common/template/list-templates.blade.php
@extends('themes.default1.admin.layout.admin')

@section('PageHeader')
<h1>{!! Lang::get('lang.templates') !!}</h1>
@stop

@section('content')
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">{!! Lang::get('lang.edit_templates') !!}</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        @if(Session::has('success'))
        <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{Session::get('success')}}
        </div>
        @endif
        @if(Session::has('failed'))
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <b>{!! Lang::get('lang.alert') !!}!</b>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <p>{{Session::get('failed')}}</p>                
        </div>
        @endif
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>{!! Lang::get('lang.type') !!}</th>
                    <th>{!! Lang::get('lang.description') !!}</th>
                    <th>{!! Lang::get('lang.action') !!}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($templates as $template)
                <tr>
                    <?php $type = App\Model\Common\TemplateType::where('id','=',$template->type)->first(); ?>
                    <td>{!! $type->name !!}</td>
                    <td>{!! $template->name !!}</td>
                    <td>
                        {!! link_to_route('templates.edit', Lang::get('lang.edit_templates'),[$template->id],['class'=>'btn btn-success btn-sm']) !!}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div><!-- /.box-body -->
</div>

<!-- status script -->
<script type="text/javascript">
$(function() {
    $("#example1").dataTable();
    $('#example2').dataTable({
        "bPaginate": true,
        "bLengthChange": false,
        "bFilter": false,
        "bSort": true,
        "bInfo": true,
        "bAutoWidth": false
    });
});
</script>
<script src="{{asset("lb-faveo/plugins/datatables/jquery.dataTables.js")}}" type="text/javascript"></script>
<script src="{{asset("lb-faveo/plugins/datatables/dataTables.bootstrap.js")}}" type="text/javascript"></script>
@stop

resources/views/themes/default1/common/template/shoppingcart.blade.php
@extends('themes.default1.layouts.front.master')
@section('title')
pricing
@stop
@section('page-header')
Pricing
@stop
@section('breadcrumb')
<li><a href="{{url('home')}}">Home</a></li>
<li class="active">Pricing</li>
@stop
@section('main-class') 
main
@stop


@section('content')


<div class="row">
    @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif

                @if(Session::has('success'))
                <div class="alert alert-success alert-dismissable">
                    <i class="fa fa-ban"></i>
                    <b>{{Lang::get('message.alert')}}!</b> {{Lang::get('message.success')}}.
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{Session::get('success')}}
                </div>
                @endif
                <!-- fail message -->
                @if(Session::has('fails'))
                <div class="alert alert-danger alert-dismissable">
                    <i class="fa fa-ban"></i>
                    <b>{{Lang::get('message.alert')}}!</b> {{Lang::get('message.failed')}}.
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{Session::get('fails')}}
                </div>
                @endif
    
    <div class="col-md-12 col-md-offset-3">
        <div class="pricing-table princig-table-flat">
        {!! html_entity_decode($template) !!}
        </div>
    </div>

</div>

@stop